#!/usr/bin/env bash
# A while loop that prints "Best School" 10 times using and  On the 9th iteration, displays "Hi" before "Best School".

count=0

while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( i++ ))
done
